In [1]:
import os
import pandas as pd

In [3]:
df = pd.read_csv(os.path.join('./results/', os.listdir('./results')[2]))
df.head()

                   image     GT          sum    euclidean       cosine
0  Tuberculosis-1449.png    PGD  Adversarial  Adversarial  Adversarial
1  Tuberculosis-1449.png  clean  Adversarial        Clean        Clean
2  Tuberculosis-2404.png    PGD  Adversarial  Adversarial  Adversarial
3  Tuberculosis-2404.png  clean  Adversarial        Clean        Clean
4  Tuberculosis-2065.png    PGD  Adversarial  Adversarial  Adversarial

In [4]:
df[df['GT'] == "clean"]

                     image     GT          sum    euclidean       cosine
1    Tuberculosis-1449.png  clean  Adversarial        Clean        Clean
3    Tuberculosis-2404.png  clean  Adversarial        Clean        Clean
5    Tuberculosis-2065.png  clean  Adversarial  Adversarial  Adversarial
7    Tuberculosis-1606.png  clean  Adversarial        Clean        Clean
9    Tuberculosis-2372.png  clean  Adversarial        Clean        Clean
..                     ...    ...          ...          ...          ...
691   Tuberculosis-801.png  clean  Adversarial        Clean        Clean
693  Tuberculosis-1871.png  clean  Adversarial        Clean        Clean
695  Tuberculosis-1403.png  clean  Adversarial  Adversarial  Adversarial
697  Tuberculosis-1929.png  clean  Adversarial        Clean        Clean
699   Tuberculosis-474.png  clean  Adversarial        Clean        Clean

[350 rows x 5 columns]